### ISSUE TITLE
https://fstabfmt.com/ gone?

### ISSUE THREAD

**Issue by hartwork** [xyproto/fstabfmt#3]
Hi!

I just tried the linked https://fstabfmt.com/ and got my browser saying "Server not found". Has the domain been discontinued?

Best, Sebastian

**Comment by xyproto** [comment]
Ah, yes, the webpage for FSTABFMT now lives at https://fstabfmt.roboticoverlords.org/.

I updated the link.

Thanks for reporting!

**Comment by hartwork** [comment]
@xyproto thanks for the fix and the clarification :+1:
